### ISSUE TITLE
Github pages responding with a 404

### ISSUE THREAD

**Issue by dangeranger** [cherimarie/gdi-rails#1]
Hello @cherimarie 

I am using your slides as a base for an upcoming class given by the Burlington GDI group, and noticed that your Github pages were responding with a 404.

http://cherimarie.github.io/gdi-core-rails/

In order to get Github pages to work I performed the following actions to pull the reveal.js submodule into the top level directory.

``` sh
# from within the top level gdi-rails repo directory
$ cd reveal.js/
$ git submodule init
$ git submodule update
$ vim readme.md
# make some trivial changes
$ git commit -am "trivial changes"
$ git checkout gh-pages
$ git merge master
$ git push origin/gh-pages
```

It took 5-10 minutes for the Github pages to appear after a `git push`

Hope this helps if you choose to have pages generated for your project.

**Comment by elstamey** [comment]
I'm looking at this for curriculum sprint, but I cannot see actual reveal.js files in the package.  While working on this, I'm going to incorporate the current GDI slides template.

**Comment by dangeranger** [comment]
Hello @elstamey if your steps will get this repository to match the official GDI curriculum templates that would be great. Given that the reveal.js files are in a submodule you will need to bring them in manually to have them directly included in the base repo.

**Comment by elstamey** [comment]
Yes, there is a standard GDI template that is accessible, and that will get roped in momentarily

**Comment by dangeranger** [comment]
Going to close this since this hasn't been responded to by the original author in over a year.
